network: sustainers.network
vendors:
  cloud:
    gcp:
      projects:
        production:
        sandbox:
        staging:
        development:
      computeUrlIds:
        production:
        sandbox:
        staging:
        development:
      dnsZone: network
      secretsBuckets:
        production:
        sandbox:
        staging:
        development:
      rolesBuckets:
        production:
        sandbox:
        staging:
        development:
      defaults:
        region: us-central1
        memory: 128Mi
        memoryOverrides:
          event-store: 256Mi
          view-store: 256Mi
  viewStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol: mongodb+srv
  eventStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol: mongodb+srv
  texting:
    twilio:
      testReceivingPhoneNumber:
        production:
        sandbox:
        staging:
        development:
      sendingPhoneNumber:
        production:
        sandbox:
        staging:
        development:
defaults:
  viewStore: mongodb
  eventStore: mongodb
  cloud: gcp
  texting: twilio
