network: sustainers.money
core:
  network: sustainers.network
  registries:
    production:
    sandbox:
    staging:
    development: us.gcr.io/development-271815
publicKeyUrls:
  production: https://fact.sustainers.network/public-key
  sandbox: https://fact.sandbox.sustainers.network/public-key
  staging: https://fact.staging.sustainers.network/public-key
  development: https://fact.development.sustainers.network/public-key
dependencies:
  sustainers.network:
    keys:
      production:
        id:
        secretName:
      sandbox:
        id:
        secretName:
      staging:
        id: some-id
        secretName: some-secret-name
      development:
        id: b695839a-164e-4b59-b73e-eb5d41ee7c9b
        secretName: sustainers-network-secret
vendors:
  cloud:
    gcp:
      projects:
        production:
        sandbox:
        staging:
        development:
      computeUrlIds:
        production:
        sandbox:
        staging:
        development:
      dnsZone: network
      secretsBuckets:
        production:
        sandbox:
        staging:
        development:
      rolesBuckets:
        production:
        sandbox:
        staging:
        development:
      defaults:
        region: us-central1
        memory: 128Mi
        memoryOverrides:
          event-store: 256Mi
          view-store: 256Mi
  viewStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol: mongodb+srv
  eventStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol: mongodb+srv
  texting:
    twilio:
      testReceivingPhoneNumber:
        production:
        sandbox:
        staging:
        development:
      sendingPhoneNumber:
        production:
        sandbox:
        staging:
        development:
defaults:
  viewStore: mongodb
  eventStore: mongodb
  cloud: gcp
  texting:
